### ISSUE TITLE
能否提供一份环境的配置

### ISSUE THREAD

**Issue by tzslg** [lkyahpu/EPI_ORM#1]
Installation
Python 3.6
Kreas 2.2.4
对应tensorflow的版本号？

**Comment by lkyahpu** [comment]
您好，相关环境配置已通过附件发送。













在 2021-01-03 20:52:42，"ligen" <notifications@github.com> 写道：

Installation
Python 3.6
Kreas 2.2.4
对应tensorflow的版本号？

—

**Comment by tzslg** [comment]
谢谢

**Comment by lkyahpu** [comment]
[requirements.txt](https://github.com/lkyahpu/EPI_ORM/files/6927883/requirements.txt)
